//! `lisa mail` — join a connected account to the Maildir the Mail app reads.
//!
//! Lisa does not speak IMAP and will not (apps/mail/README.md "Sync is
//! somebody else's job"). What was missing was not a mail client, it was
//! the wiring: GNOME Online Accounts holds an OAuth2 token, `mbsync`
//! turns IMAP into a Maildir, and nothing wrote the config that lets
//! them talk. This module is that config, plus the token helper mbsync
//! calls to get a fresh credential each run.
//!
//! # What is deliberately conservative
//!
//! **Nothing here can destroy mail on the server.** `Expunge None` on
//! both sides means a message can be flagged deleted and never actually
//! removed; `Remove None` means a folder that vanishes locally does not
//! take its remote twin with it. The Mail app's own Trash button is a
//! move for the same reason. A first release of a sync path is the worst
//! possible place to find out that a filename bug propagates.
//!
//! **The config is ours, at our own path.** `~/.mbsyncrc` is where a
//! person's hand-written config lives, and writing there would silently
//! replace it. We write `~/.config/lisa/mbsyncrc` and always pass `-c`.

use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

/// A mail account, reduced to what a syncer needs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Account {
    /// GOA's object id — used to ask for a token later.
    pub id: String,
    pub identity: String,
    pub imap_host: String,
    pub imap_user: String,
    /// `true` for implicit TLS on 993 (`ImapUseSsl`), which is what
    /// Gmail advertises. `false` means STARTTLS on 143.
    pub imap_ssl: bool,
    /// Submission host, when the account reports one. GOA does for
    /// Google (`smtp.gmail.com`); derived from the IMAP host otherwise.
    pub smtp_host: Option<String>,
}

/// How mbsync proves who we are.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Credential {
    /// An OAuth2 token, fetched per run from Online Accounts. Needs the
    /// XOAUTH2 SASL mechanism (os/packages/cyrus-sasl-xoauth2).
    OnlineAccount,
    /// A provider-issued app password, read from a file. Works with
    /// stock isync and with providers that offer nothing else.
    AppPassword { file: PathBuf },
}

/// Where everything lives.
#[derive(Debug, Clone)]
pub struct Paths {
    pub maildir: PathBuf,
    pub config: PathBuf,
    pub send_config: PathBuf,
}

impl Paths {
    pub fn new(home: &Path, maildir: Option<PathBuf>) -> Self {
        Self {
            maildir: maildir.unwrap_or_else(|| home.join("Mail")),
            config: home.join(".config/lisa/mbsyncrc"),
            // Ours, at our own path, for the same reason as mbsyncrc:
            // ~/.msmtprc is where a person's hand-written config lives.
            send_config: home.join(".config/lisa/msmtprc"),
        }
    }
}

/// Written into every generated config so we can tell our file from a
/// hand-written one and refuse to clobber the latter.
pub const MARKER: &str = "# Generated by `lisa mail setup`. Edits are lost on the next run.";

/// Gmail's special folders, mapped to the names the Mail app orders by
/// (apps/mail `FOLDER_ORDER`).
///
/// `[Gmail]/All Mail` is deliberately absent: it contains a copy of
/// every message in every other folder, so syncing it doubles the disk
/// and shows every message twice.
const GMAIL_FOLDERS: &[(&str, &str)] = &[
    ("INBOX", "INBOX"),
    ("[Gmail]/Sent Mail", "Sent"),
    ("[Gmail]/Drafts", "Drafts"),
    ("[Gmail]/Trash", "Trash"),
    ("[Gmail]/Spam", "Spam"),
];

/// Non-Gmail servers: sync the inbox and whatever else exists by name.
const GENERIC_FOLDERS: &[(&str, &str)] = &[
    ("INBOX", "INBOX"),
    ("Sent", "Sent"),
    ("Drafts", "Drafts"),
    ("Trash", "Trash"),
];

fn is_gmail(host: &str) -> bool {
    let host = host.to_ascii_lowercase();
    host == "imap.gmail.com" || host.ends_with(".gmail.com") || host == "imap.googlemail.com"
}

/// Quote a value for mbsync's config grammar.
///
/// Folder names are the reason this exists: `[Gmail]/Sent Mail` has a
/// space in it, and an unquoted space ends the value.
fn quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', r"\\").replace('"', "\\\""))
}

/// A name safe to use as a directory and as an mbsync identifier.
///
/// The account's address with the characters that mean something to a
/// path or to mbsync's grammar removed. `you@example.com` becomes
/// `you_at_example.com`, which is still recognisable in a file manager —
/// the Maildir is a directory a person will open one day.
pub fn slug(address: &str) -> String {
    let cleaned: String = address
        .trim()
        .replace('@', "_at_")
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    // `.` and `..` survive the filter above because a dot is legal in
    // an address, and both name a directory OUTSIDE the one we are
    // building a path in. An address is never literally `..`; a
    // function that can emit it is still a path-traversal waiting for
    // the day something else calls it.
    if cleaned.is_empty() || cleaned.chars().all(|c| c == '.') {
        "account".into()
    } else {
        cleaned
    }
}

/// Where one account's mail lives under the Maildir root.
///
/// Each account gets its own subtree. A shared tree would merge two
/// people's inboxes into one folder with no way to tell them apart, and
/// "which account is this from" is the question the sidebar exists to
/// answer.
pub fn account_root(maildir: &Path, address: &str, multi: bool) -> PathBuf {
    if multi {
        maildir.join(slug(address))
    } else {
        maildir.to_path_buf()
    }
}

/// The whole config file, as text.
///
/// Pure on purpose — this is the part that is easy to get subtly wrong
/// and impossible to notice, because a config that parses but names the
/// wrong folder syncs nothing and reports success.
///
/// With more than one account, each gets its own store, its own channels
/// and its own subtree; the single group syncs all of them, so
/// `lisa mail sync` stays one command.
pub fn render_mbsyncrc(accounts: &[Account], paths: &Paths, credential: &Credential) -> String {
    let mut out = String::new();
    out.push_str(MARKER);
    out.push_str("\n#\n# Run it with:  lisa mail sync\n\n");

    let multi = accounts.len() > 1;
    let mut channels = Vec::new();

    for account in accounts {
        let id = if multi {
            slug(&account.identity)
        } else {
            "lisa".to_string()
        };
        let root = account_root(&paths.maildir, &account.identity, multi);

        out.push_str(&format!("IMAPAccount {id}\n"));
        out.push_str(&format!("Host {}\n", account.imap_host));
        out.push_str(&format!("User {}\n", account.imap_user));

        match credential {
            Credential::OnlineAccount => {
                // A token, not a password: it expires in about an hour,
                // so it is fetched per run rather than written here.
                // `--account` names WHICH account to ask for, because
                // with several connected the helper cannot guess.
                out.push_str(&format!(
                    "PassCmd {}\n",
                    quote(&format!("lisa mail token --account {}", account.id))
                ));
                out.push_str("AuthMechs XOAUTH2\n");
            }
            Credential::AppPassword { file } => {
                out.push_str(&format!(
                    "PassCmd {}\n",
                    quote(&format!("cat {}", file.display()))
                ));
                out.push_str("AuthMechs LOGIN\n");
            }
        }

        if account.imap_ssl {
            out.push_str("TLSType IMAPS\n");
        } else {
            out.push_str("TLSType STARTTLS\n");
        }
        out.push_str("CertificateFile /etc/ssl/certs/ca-certificates.crt\n\n");

        out.push_str(&format!("IMAPStore {id}-remote\nAccount {id}\n\n"));
        out.push_str(&format!("MaildirStore {id}-local\n"));
        out.push_str(&format!("Path {}/\n", root.display()));
        out.push_str(&format!("Inbox {}/INBOX\n", root.display()));
        // Verbatim: folder names on disk are the names the Mail app
        // shows, so a folder called Archive is a directory called
        // Archive.
        out.push_str("SubFolders Verbatim\n\n");

        let folders = if is_gmail(&account.imap_host) {
            GMAIL_FOLDERS
        } else {
            GENERIC_FOLDERS
        };
        for (remote, local) in folders {
            let channel = format!("{id}-{}", local.to_ascii_lowercase());
            out.push_str(&format!("Channel {channel}\n"));
            out.push_str(&format!("Far :{id}-remote:{}\n", quote(remote)));
            out.push_str(&format!("Near :{id}-local:{}\n", quote(local)));
            // Create Near only: local folders appear as needed, and
            // nothing this machine does creates a folder in somebody
            // else's account.
            out.push_str("Create Near\n");
            // Neither side ever expunges, and neither side removes a
            // folder because the other lost it. Together these mean a
            // bug here costs flags, never messages.
            out.push_str("Expunge None\n");
            out.push_str("Remove None\n");
            out.push_str("SyncState *\n\n");
            channels.push(channel);
        }
    }

    out.push_str("Group lisa\n");
    for name in &channels {
        out.push_str(&format!("Channel {name}\n"));
    }
    out.push('\n');
    out
}

/// The sending half, as text.
///
/// msmtp rather than a client of our own: same reasoning as mbsync for
/// receiving. It implements XOAUTH2 natively instead of through Cyrus
/// SASL, so this needs no plugin — `passwordeval` runs the same token
/// helper mbsync uses.
///
/// One account block each plus a default, so `msmtp -a <slug>` picks the
/// identity and a bare `msmtp` still works.
pub fn render_msmtprc(accounts: &[Account], credential: &Credential) -> String {
    let mut out = String::new();
    out.push_str(MARKER);
    out.push_str("\n#\n# Sending half. Receiving is mbsyncrc, next to this file.\n\n");
    out.push_str("defaults\ntls on\ntls_trust_file /etc/ssl/certs/ca-certificates.crt\n");
    // A log is how a person finds out why a message did not leave. Under
    // the user's own state directory, never /var: mail is theirs.
    out.push_str("logfile ~/.local/state/lisa/msmtp.log\n\n");

    for account in accounts {
        let id = slug(&account.identity);
        // Gmail's submission host is smtp.<domain> where IMAP is
        // imap.<domain>; deriving it beats hardcoding one provider, and
        // GOA reports it directly for accounts that have it.
        let host = account
            .smtp_host
            .clone()
            .unwrap_or_else(|| account.imap_host.replacen("imap.", "smtp.", 1));
        out.push_str(&format!("account {id}\n"));
        out.push_str(&format!("host {host}\n"));
        out.push_str("port 587\n");
        out.push_str("tls_starttls on\n");
        out.push_str(&format!("from {}\n", account.identity));
        out.push_str(&format!("user {}\n", account.imap_user));
        match credential {
            Credential::OnlineAccount => {
                out.push_str("auth xoauth2\n");
                out.push_str(&format!(
                    "passwordeval \"lisa mail token --account {}\"\n",
                    account.id
                ));
            }
            Credential::AppPassword { file } => {
                out.push_str("auth on\n");
                out.push_str(&format!("passwordeval \"cat {}\"\n", file.display()));
            }
        }
        out.push('\n');
    }
    if let Some(first) = accounts.first() {
        out.push_str(&format!("account default : {}\n", slug(&first.identity)));
    }
    out
}

/// Refuse to overwrite a config we did not write.
pub fn may_write(existing: Option<&str>) -> bool {
    match existing {
        None => true,
        Some(text) => text.contains(MARKER),
    }
}

// ---------------------------------------------------------------------
// The parts that touch the world.
// ---------------------------------------------------------------------

const GOA_SERVICE: &str = "org.gnome.OnlineAccounts";
const GOA_PATH: &str = "/org/gnome/OnlineAccounts";

fn home() -> Result<PathBuf> {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is unset, so there is nowhere to put a Maildir")
}

fn session_bus() -> Result<zbus::blocking::Connection> {
    zbus::blocking::Connection::session().context(
        "no session bus — `lisa mail` configures a desktop account and has to run in your session",
    )
}

/// Every account Online Accounts knows about that has mail switched on.
///
/// Read straight off the object manager rather than through a generated
/// proxy: three properties are wanted and the interface is stable.
pub fn accounts() -> Result<Vec<Account>> {
    let conn = session_bus()?;
    let proxy = zbus::blocking::Proxy::new(
        &conn,
        GOA_SERVICE,
        GOA_PATH,
        "org.freedesktop.DBus.ObjectManager",
    )
    .context("Online Accounts is not on the session bus")?;

    type Managed = std::collections::HashMap<
        zbus::zvariant::OwnedObjectPath,
        std::collections::HashMap<
            String,
            std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
        >,
    >;
    let managed: Managed = proxy
        .call("GetManagedObjects", &())
        .context("could not list online accounts")?;

    let text = |map: &std::collections::HashMap<String, zbus::zvariant::OwnedValue>, key: &str| {
        map.get(key)
            .and_then(|v| String::try_from(v.clone()).ok())
            .unwrap_or_default()
    };
    let flag = |map: &std::collections::HashMap<String, zbus::zvariant::OwnedValue>, key: &str| {
        map.get(key)
            .and_then(|v| bool::try_from(v.clone()).ok())
            .unwrap_or(false)
    };

    let mut out = Vec::new();
    for (path, interfaces) in managed {
        let Some(account) = interfaces.get("org.gnome.OnlineAccounts.Account") else {
            continue;
        };
        // An account with no Mail interface is a calendar or contacts
        // account; one with MailDisabled is a person's explicit choice.
        let Some(mail) = interfaces.get("org.gnome.OnlineAccounts.Mail") else {
            continue;
        };
        if flag(account, "MailDisabled") {
            continue;
        }
        out.push(Account {
            id: path
                .as_str()
                .rsplit('/')
                .next()
                .unwrap_or_default()
                .to_string(),
            identity: text(account, "PresentationIdentity"),
            imap_host: text(mail, "ImapHost"),
            imap_user: text(mail, "ImapUserName"),
            imap_ssl: flag(mail, "ImapUseSsl"),
            smtp_host: Some(text(mail, "SmtpHost")).filter(|h| !h.is_empty()),
        });
    }
    out.sort_by(|a, b| a.identity.cmp(&b.identity));
    Ok(out)
}

/// Print a fresh OAuth2 access token. This is what mbsync's `PassCmd`
/// runs, once per sync.
///
/// It writes a credential to stdout, which is the whole job, so it does
/// exactly that and nothing else: no logging, no ledger entry carrying
/// the value, no copy on disk. The token lasts about an hour, which is
/// why it is fetched rather than stored.
pub fn token(account_id: Option<String>) -> Result<()> {
    let id = match account_id {
        // Accept either the GOA object id or the address: the config
        // written by `setup` uses the id, and a person typing this by
        // hand will reach for the address.
        Some(want) => {
            if want.starts_with("account_") {
                want
            } else {
                let found = accounts()?;
                let Some(hit) = found
                    .iter()
                    .find(|a| a.identity == want || a.imap_user == want)
                else {
                    bail!("no connected account matches {want:?}");
                };
                hit.id.clone()
            }
        }
        None => {
            let found = accounts()?;
            let Some(first) = found.first() else {
                bail!("no online account with mail enabled — connect one in Settings");
            };
            first.id.clone()
        }
    };
    let conn = session_bus()?;

    // Refuse to call GOA while the login keyring is locked. GetAccessToken
    // does not fail in that state — GOA parks it behind a Secret Service
    // unlock prompt, which on a rebooted autologin machine is drawn for
    // nobody, so the call simply never returns. Everything downstream
    // inherits the hang: mbsync sits in "xoauth2: step1", msmtp sits in
    // passwordeval, and lisa-mail-sync.service reads "activating"
    // forever. Seen on the reference iMac 2026-08-03. A bounded, named
    // failure here turns all of that into one actionable line.
    if login_keyring_locked(&conn) {
        bail!(
            "the login keyring is locked, so no account can hand over a token.\n\
             This happens after every reboot: autologin starts the session but \
             never unlocks the keyring. Unlock it once at the machine (any app \
             that touches a credential will prompt), then mail resumes on its own."
        );
    }

    let proxy = zbus::blocking::Proxy::new(
        &conn,
        GOA_SERVICE,
        format!("{GOA_PATH}/Accounts/{id}"),
        "org.gnome.OnlineAccounts.OAuth2Based",
    )
    .context("that account does not use OAuth2")?;

    let (token, _expires): (String, i32) = proxy.call("GetAccessToken", &()).context(
        "Online Accounts would not hand over a token. If it says the keyring failed, this \
         system has no credential store — see `lisa mail status`",
    )?;
    println!("{token}");
    Ok(())
}

/// Is the Secret Service's `login` collection locked?
///
/// Property read, not an Unlock attempt: reading `Locked` never
/// prompts, so this can be called from a headless path safely. Errors
/// count as "not locked" — a system with no Secret Service at all is
/// diagnosed by `has_secret_service` with its own message, and failing
/// open here means a broken property read degrades to today's
/// behaviour instead of inventing a new refusal.
fn login_keyring_locked(conn: &zbus::blocking::Connection) -> bool {
    zbus::blocking::Proxy::new(
        conn,
        "org.freedesktop.secrets",
        "/org/freedesktop/secrets/collection/login",
        "org.freedesktop.DBus.Properties",
    )
    .and_then(|p| {
        p.call::<_, _, zbus::zvariant::OwnedValue>(
            "Get",
            &("org.freedesktop.Secret.Collection", "Locked"),
        )
    })
    .ok()
    .and_then(|v| bool::try_from(v).ok())
    .unwrap_or(false)
}

/// Is the XOAUTH2 SASL mechanism installed?
///
/// Checked by looking for the plugin rather than by trying to
/// authenticate: without it mbsync fails at connection time with
/// "unsupported authentication mechanism", which reads like a server
/// problem and is not one.
fn has_xoauth2() -> bool {
    ["/usr/lib/sasl2", "/usr/lib64/sasl2", "/usr/local/lib/sasl2"]
        .iter()
        .any(|dir| Path::new(dir).join("libxoauth2.so").exists())
}

fn has_secret_service() -> bool {
    let Ok(conn) = session_bus() else {
        return false;
    };
    let Ok(proxy) = zbus::blocking::Proxy::new(
        &conn,
        "org.freedesktop.DBus",
        "/org/freedesktop/DBus",
        "org.freedesktop.DBus",
    ) else {
        return false;
    };
    proxy
        .call::<_, _, bool>("NameHasOwner", &("org.freedesktop.secrets",))
        .unwrap_or(false)
        || proxy
            .call::<_, _, Vec<String>>("ListActivatableNames", &())
            .map(|names| names.iter().any(|n| n == "org.freedesktop.secrets"))
            .unwrap_or(false)
}

fn which(program: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|path| {
        std::env::split_paths(&path)
            .map(|dir| dir.join(program))
            .find(|candidate| candidate.is_file())
    })
}

/// `lisa mail status` — the same question the app's settings page
/// answers, from a terminal and from inside a diagnostic.
pub fn status() -> Result<()> {
    let home = home()?;
    let paths = Paths::new(&home, None);

    let mbsync = which("mbsync");
    println!(
        "syncer:      {}",
        mbsync
            .as_ref()
            .map(|p| p.display().to_string())
            .unwrap_or_else(|| "not installed".into())
    );
    println!(
        "XOAUTH2:     {}",
        if has_xoauth2() {
            "available"
        } else {
            "missing — an Online Accounts token cannot be used"
        }
    );
    println!(
        "keyring:     {}",
        if has_secret_service() {
            "present"
        } else {
            "absent — Online Accounts can hold an account but no credential"
        }
    );

    match accounts() {
        Ok(found) if found.is_empty() => println!("accounts:    none with mail enabled"),
        Ok(found) => {
            for account in &found {
                println!(
                    "account:     {} ({}, {})",
                    account.identity,
                    account.imap_host,
                    if account.imap_ssl {
                        "IMAPS"
                    } else {
                        "STARTTLS"
                    }
                );
            }
        }
        Err(e) => println!("accounts:    unavailable ({e})"),
    }

    println!(
        "config:      {}",
        if paths.config.exists() {
            paths.config.display().to_string()
        } else {
            "not written — run `lisa mail setup`".into()
        }
    );
    println!("maildir:     {}", paths.maildir.display());
    Ok(())
}

/// `lisa mail setup` — write the config that joins the two halves.
pub fn setup(app_password: Option<PathBuf>, maildir: Option<PathBuf>, force: bool) -> Result<()> {
    let home = home()?;
    let paths = Paths::new(&home, maildir);

    let found = accounts()?;
    if found.is_empty() {
        bail!(
            "no online account with mail enabled.\n\
             Connect one in Settings under Online Accounts, then run this again."
        );
    }
    // ALL of them, not the first. Picking one silently meant a person
    // with a work account and a personal one discovered which we chose
    // by reading their own mail; and with an app password, which is one
    // account's credential, only that account is configured.
    let selected: Vec<Account> = match &app_password {
        Some(_) if found.len() > 1 => {
            println!(
                "note: an app password belongs to one account; using {}",
                found[0].identity
            );
            vec![found[0].clone()]
        }
        _ => found.clone(),
    };

    let credential = match app_password {
        Some(file) => {
            if !file.exists() {
                bail!("no password file at {}", file.display());
            }
            Credential::AppPassword { file }
        }
        None => {
            if !has_xoauth2() {
                bail!(
                    "this system has no XOAUTH2 SASL mechanism, so mbsync cannot use the token \
                     Online Accounts holds.\n\
                     Update to an image carrying cyrus-sasl-xoauth2, or use an app password:\n  \
                     lisa mail setup --app-password ~/.mail-password"
                );
            }
            if !has_secret_service() {
                bail!(
                    "this system has no credential store, so Online Accounts cannot produce a \
                     token (issue #154).\n\
                     Update to an image carrying gnome-keyring, or use an app password:\n  \
                     lisa mail setup --app-password ~/.mail-password"
                );
            }
            Credential::OnlineAccount
        }
    };

    let existing = std::fs::read_to_string(&paths.config).ok();
    if !force && !may_write(existing.as_deref()) {
        bail!(
            "{} was not written by this command and will not be replaced.\n\
             Move it aside, or pass --force.",
            paths.config.display()
        );
    }

    if let Some(parent) = paths.config.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("could not create {}", parent.display()))?;
    }
    std::fs::create_dir_all(&paths.maildir)
        .with_context(|| format!("could not create {}", paths.maildir.display()))?;

    let text = render_mbsyncrc(&selected, &paths, &credential);
    std::fs::write(&paths.config, &text)
        .with_context(|| format!("could not write {}", paths.config.display()))?;

    // The sending half. Written now rather than when sending is first
    // attempted: the credential and the account list are in hand here,
    // and a config that appears only after a failure is a config nobody
    // finds. It carries no secret — the token comes from the same helper
    // at send time — so 0600 is belt-and-braces rather than the point.
    let send = render_msmtprc(&selected, &credential);
    std::fs::write(&paths.send_config, &send)
        .with_context(|| format!("could not write {}", paths.send_config.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ =
            std::fs::set_permissions(&paths.send_config, std::fs::Permissions::from_mode(0o600));
    }

    for account in &selected {
        let root = account_root(&paths.maildir, &account.identity, selected.len() > 1);
        std::fs::create_dir_all(&root)
            .with_context(|| format!("could not create {}", root.display()))?;
        println!("account:  {}  ->  {}", account.identity, root.display());
    }
    println!("config:   {}", paths.config.display());
    println!("sending:  {}", paths.send_config.display());
    println!("maildir:  {}", paths.maildir.display());
    match enable_timer() {
        Ok(true) => println!("timer:    every 5 minutes (lisa-mail-sync.timer)"),
        Ok(false) => println!("timer:    not installed — run `lisa mail sync` yourself"),
        Err(e) => println!("timer:    could not enable it ({e}); `lisa mail sync` still works"),
    }
    println!("\nFetch now with:  lisa mail sync");
    Ok(())
}

/// Turn on the periodic sync.
///
/// Here rather than in the package, because a timer that fires every
/// five minutes to report "there is no config" is a recurring failure
/// in the journal of somebody who never asked for mail. Setting mail up
/// is the moment it starts making sense.
///
/// A missing unit is not an error: the CLI updates on a different
/// channel from the OS image (ADR-0020), so a newer `lisa` on an older
/// image is a supported state, and there the config still works by hand.
fn enable_timer() -> Result<bool> {
    let unit = "lisa-mail-sync.timer";
    let installed = ["/usr/lib/systemd/user", "/etc/systemd/user"]
        .iter()
        .any(|dir| Path::new(dir).join(unit).exists());
    if !installed {
        return Ok(false);
    }
    let status = std::process::Command::new("systemctl")
        .args(["--user", "enable", "--now", unit])
        .status()
        .context("could not run systemctl")?;
    if !status.success() {
        bail!("systemctl exited with {status}");
    }
    Ok(true)
}

/// `lisa mail sync` — one pass of the syncer.
pub fn sync() -> Result<()> {
    let home = home()?;
    let paths = Paths::new(&home, None);
    if !paths.config.exists() {
        bail!("no config yet — run `lisa mail setup` first");
    }
    let Some(mbsync) = which("mbsync") else {
        bail!("mbsync is not installed; Lisa does not sync mail itself (apps/mail/README.md)");
    };

    // -c: our config, never ~/.mbsyncrc. `lisa` is the group name every
    // generated config defines.
    let status = std::process::Command::new(mbsync)
        .arg("-c")
        .arg(&paths.config)
        .arg("lisa")
        .status()
        .context("could not run mbsync")?;
    if !status.success() {
        bail!("mbsync exited with {status}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn account() -> Account {
        Account {
            id: "account_1785335038_0".into(),
            identity: "someone@example.test".into(),
            imap_host: "imap.gmail.com".into(),
            imap_user: "someone@example.test".into(),
            imap_ssl: true,
            smtp_host: Some("smtp.gmail.com".into()),
        }
    }

    fn paths() -> Paths {
        Paths::new(Path::new("/home/lisa"), None)
    }

    #[test]
    fn a_folder_with_a_space_survives_the_config_grammar() {
        // `[Gmail]/Sent Mail` unquoted ends at the space, and mbsync
        // then syncs a folder called `[Gmail]/Sent`, which does not
        // exist — reporting success and copying nothing.
        let text = render_mbsyncrc(&[account()], &paths(), &Credential::OnlineAccount);
        assert!(
            text.contains(r#"Far :lisa-remote:"[Gmail]/Sent Mail""#),
            "{text}"
        );
        assert!(text.contains(r#"Near :lisa-local:"Sent""#), "{text}");
    }

    #[test]
    fn nothing_generated_here_can_destroy_mail_on_the_server() {
        // The invariant worth a test: every channel refuses to expunge
        // and refuses to remove. A first sync release is the worst place
        // to discover that a filename bug propagates.
        let text = render_mbsyncrc(&[account()], &paths(), &Credential::OnlineAccount);
        let channels = text.matches("Channel ").count() - 1; // minus the Group's list header
        assert!(channels >= 5, "expected the gmail folder set: {text}");
        assert_eq!(text.matches("Expunge None").count(), GMAIL_FOLDERS.len());
        assert_eq!(text.matches("Remove None").count(), GMAIL_FOLDERS.len());
        // …and never creates a folder in somebody's account.
        assert_eq!(text.matches("Create Near").count(), GMAIL_FOLDERS.len());
        assert!(!text.contains("Create Both"), "{text}");
        assert!(!text.contains("Create Far"), "{text}");
    }

    #[test]
    fn all_mail_is_not_synced() {
        // It holds a copy of every message in every other folder:
        // syncing it doubles the disk and shows everything twice.
        let text = render_mbsyncrc(&[account()], &paths(), &Credential::OnlineAccount);
        assert!(!text.contains("All Mail"), "{text}");
    }

    #[test]
    fn the_token_is_fetched_per_run_and_never_written_down() {
        let text = render_mbsyncrc(&[account()], &paths(), &Credential::OnlineAccount);
        // Names WHICH account: with several connected, a helper that
        // has to guess will eventually guess wrong and authenticate one
        // mailbox with another's token.
        assert!(
            text.contains(r#"PassCmd "lisa mail token --account account_1785335038_0""#),
            "{text}"
        );
        assert!(text.contains("AuthMechs XOAUTH2"), "{text}");
        // An access token lasts about an hour. A config carrying one
        // would work exactly once and then look like a broken account.
        assert!(!text.to_lowercase().contains("pass "), "{text}");
    }

    #[test]
    fn an_app_password_uses_a_mechanism_stock_isync_has() {
        // The point of this path: it needs no SASL plugin, so it works
        // on an image that predates os/packages/cyrus-sasl-xoauth2 and
        // on providers that offer no OAuth at all.
        let credential = Credential::AppPassword {
            file: PathBuf::from("/home/lisa/.mail-password"),
        };
        let text = render_mbsyncrc(&[account()], &paths(), &credential);
        assert!(text.contains("AuthMechs LOGIN"), "{text}");
        assert!(
            text.contains(r#"PassCmd "cat /home/lisa/.mail-password""#),
            "{text}"
        );
        assert!(!text.contains("XOAUTH2"), "{text}");
    }

    #[test]
    fn tls_follows_what_the_account_actually_said() {
        let mut a = account();
        assert!(
            render_mbsyncrc(
                std::slice::from_ref(&a),
                &paths(),
                &Credential::OnlineAccount
            )
            .contains("TLSType IMAPS")
        );
        // ImapUseSsl=false means STARTTLS on 143 — asserting IMAPS there
        // would fail to connect at all.
        a.imap_ssl = false;
        let text = render_mbsyncrc(
            std::slice::from_ref(&a),
            &paths(),
            &Credential::OnlineAccount,
        );
        assert!(text.contains("TLSType STARTTLS"), "{text}");
        // `TLSType IMAPS`, not `IMAPS` — the substring also occurs in
        // `IMAPStore`, which made the first version of this assertion
        // fail against correct output.
        assert!(!text.contains("TLSType IMAPS"), "{text}");
    }

    #[test]
    fn a_non_gmail_server_does_not_get_gmails_folder_names() {
        let mut a = account();
        a.imap_host = "imap.fastmail.com".into();
        let text = render_mbsyncrc(
            std::slice::from_ref(&a),
            &paths(),
            &Credential::OnlineAccount,
        );
        assert!(!text.contains("[Gmail]"), "{text}");
        assert!(text.contains(r#"Far :lisa-remote:"Sent""#), "{text}");
        // …and googlemail is gmail.
        a.imap_host = "imap.googlemail.com".into();
        assert!(
            render_mbsyncrc(
                std::slice::from_ref(&a),
                &paths(),
                &Credential::OnlineAccount
            )
            .contains("[Gmail]")
        );
    }

    fn second() -> Account {
        Account {
            id: "account_1785447543_1".into(),
            identity: "other@gmail.test".into(),
            imap_host: "imap.gmail.com".into(),
            imap_user: "other@gmail.test".into(),
            imap_ssl: true,
            smtp_host: Some("smtp.gmail.com".into()),
        }
    }

    #[test]
    fn two_accounts_never_share_a_maildir() {
        // The failure this prevents is unrecoverable by hand: two
        // mailboxes syncing into one folder, with no way afterwards to
        // tell which message came from which account.
        let text = render_mbsyncrc(&[account(), second()], &paths(), &Credential::OnlineAccount);
        assert!(
            text.contains("Path /home/lisa/Mail/someone_at_example.test/"),
            "{text}"
        );
        assert!(
            text.contains("Path /home/lisa/Mail/other_at_gmail.test/"),
            "{text}"
        );
        // …and each fetches its own credential.
        assert!(text.contains("--account account_1785335038_0"), "{text}");
        assert!(text.contains("--account account_1785447543_1"), "{text}");
    }

    #[test]
    fn one_account_keeps_the_flat_layout_it_already_has() {
        // A single account must not be moved into a subdirectory: mail
        // is already synced there, and silently relocating somebody's
        // Maildir is not a migration, it is a disappearance.
        let text = render_mbsyncrc(&[account()], &paths(), &Credential::OnlineAccount);
        assert!(text.contains("Path /home/lisa/Mail/\n"), "{text}");
        assert!(!text.contains("someone_at_example.test"), "{text}");
        assert_eq!(
            account_root(Path::new("/m"), "a@b.test", false),
            PathBuf::from("/m")
        );
        assert_eq!(
            account_root(Path::new("/m"), "a@b.test", true),
            PathBuf::from("/m/a_at_b.test")
        );
    }

    #[test]
    fn every_channel_name_is_unique_across_accounts() {
        // mbsync channels share one namespace. Two accounts both naming
        // a channel `inbox` is a config that parses and syncs one
        // mailbox twice.
        let text = render_mbsyncrc(&[account(), second()], &paths(), &Credential::OnlineAccount);
        let names: Vec<&str> = text
            .lines()
            .filter_map(|l| l.strip_prefix("Channel "))
            .collect();
        let unique: std::collections::HashSet<&&str> = names.iter().collect();
        // Each channel is declared once and listed once in the group.
        assert_eq!(names.len(), unique.len() * 2, "{names:?}");
        assert!(
            names
                .iter()
                .any(|n| n.starts_with("someone_at_example.test-")),
            "{names:?}"
        );
    }

    #[test]
    fn an_address_becomes_a_name_a_person_can_recognise() {
        // The Maildir is a directory somebody will open in a file
        // manager one day.
        assert_eq!(slug("you@example.com"), "you_at_example.com");
        assert_eq!(slug("Odd Name+tag@x.test"), "Odd_Name_tag_at_x.test");
        assert_eq!(slug("../../etc/passwd"), ".._.._etc_passwd");
        assert_eq!(slug(""), "account");
        // No separator survives, so a slug can never climb out of the
        // Maildir root.
        for s in ["a/b@c", "a\\b@c", "..", "a\0b"] {
            let out = slug(s);
            assert!(
                !out.contains('/') && !out.contains('\\') && out != "..",
                "{s} -> {out}"
            );
        }
    }

    #[test]
    fn sending_uses_the_same_token_helper_and_never_stores_a_credential() {
        let text = render_msmtprc(&[account()], &Credential::OnlineAccount);
        assert!(text.contains("auth xoauth2"), "{text}");
        assert!(
            text.contains(r#"passwordeval "lisa mail token --account account_1785335038_0""#),
            "{text}"
        );
        // GOA reports SmtpAuthLogin=false and SmtpAuthPlain=false for
        // the connected Google account: XOAUTH2 is the only mechanism
        // that would work, so offering another would just fail later.
        assert!(!text.contains("auth on"), "{text}");
        assert!(text.contains("host smtp.gmail.com"), "{text}");
    }

    #[test]
    fn a_submission_host_is_derived_when_the_account_does_not_report_one() {
        // Not every provider tells us. Deriving smtp.<domain> from
        // imap.<domain> beats hardcoding one provider's hostnames.
        let mut a = account();
        a.smtp_host = None;
        a.imap_host = "imap.fastmail.com".into();
        let text = render_msmtprc(std::slice::from_ref(&a), &Credential::OnlineAccount);
        assert!(text.contains("host smtp.fastmail.com"), "{text}");
    }

    #[test]
    fn each_account_can_send_as_itself() {
        // Sending from the wrong address is the mail equivalent of
        // syncing two mailboxes into one folder: recoverable, but only
        // after somebody has already read it.
        let text = render_msmtprc(&[account(), second()], &Credential::OnlineAccount);
        assert!(text.contains("from someone@example.test"), "{text}");
        assert!(text.contains("from other@gmail.test"), "{text}");
        assert!(text.contains("--account account_1785335038_0"), "{text}");
        assert!(text.contains("--account account_1785447543_1"), "{text}");
        // A bare `msmtp` has to pick something, and picking silently is
        // worse than picking predictably.
        assert!(
            text.contains("account default : someone_at_example.test"),
            "{text}"
        );
    }

    #[test]
    fn a_hand_written_config_is_never_overwritten() {
        // ~/.mbsyncrc is somebody's own file. This one is ours, at our
        // own path, and even there we check before replacing.
        assert!(may_write(None));
        assert!(may_write(Some(&format!("{MARKER}\nIMAPAccount lisa\n"))));
        assert!(!may_write(Some(
            "IMAPAccount mine\nHost imap.example.test\n"
        )));
    }

    #[test]
    fn the_maildir_is_where_the_app_looks() {
        let p = Paths::new(Path::new("/home/lisa"), None);
        assert_eq!(p.maildir, PathBuf::from("/home/lisa/Mail"));
        assert_eq!(p.config, PathBuf::from("/home/lisa/.config/lisa/mbsyncrc"));
        // …and an override is honoured, because the app has one too.
        let p = Paths::new(Path::new("/home/lisa"), Some(PathBuf::from("/srv/mail")));
        assert_eq!(p.maildir, PathBuf::from("/srv/mail"));
    }
}
